version: 2.1
jobs:

  erlang-medium_j2:
    machine:
      image: ubuntu-2004:current
      resource_class: medium
    steps:
      - checkout
      - run:
          name: circle-medium_j2
          environment:
            a_type: circle-medium_j2
          command: |
            bash benchmarks/erlang_setup.sh
            make bench J="2" AGENT_TYPE="$a_type" BENCHMARK_NAME="erlang" BENCH=benchmarks/ubuntu_erlang.sh

workflows:
  arm:
    jobs:
      - erlang-medium_j2
