version: 2.1
jobs:

  erlang-large_j2:
    docker:
      - image: cimg/base:current
    resource_class: medium
    steps:
      - checkout
      - run:
          name: circle-docker-medium_j2
          environment:
            a_type: circle-docker-medium_j2
          command: |
            bash benchmarks/erlang_setup.sh
            make bench J="2" AGENT_TYPE="$a_type" BENCHMARK_NAME="erlang" BENCH=benchmarks/ubuntu_erlang.sh

workflows:
  large:
    jobs:
      - erlang-large_j2
